services:
  - type: web
    env: static
    buildCommand: |
      echo "Using render.yaml configuration"
      cd application
      npm run build
      echo "Build complete - checking dist folder:"
      ls -la dist/
    staticPublishPath: ./application/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html